### ISSUE TITLE
CocoaPod

### ISSUE THREAD

**Issue by imclean** [payleven/Point-Pay-SDK-iOS#5]
This doesn't work anymore, are you going to fix it?

**Comment by mpodeszwa** [comment]
I agree, I am able to get only version 1.1.0

**Comment by konradfeketepayleven** [comment]
Hi,

Thanks for reaching out! 
I apologize for any inconvenience this may have caused! 
From now on this shouldn't be a problem anymore as we just updated CocoaPods. 
Please refer to:
pod 'Payleven-mPos', '~> 1.2.1'

Best regards
