### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by mpodeszwa** [payleven/Point-Pay-SDK-iOS#6]
Is it possible to get framework with bitcode support? Maybe another branch?
````
ld: '/Users/marcinpodeszwa/Documents/Inventorum/ios/Pods/Payleven-mPos/Framework/AdyenToolkit.framework/AdyenToolkit(ADYFMDBDatabase.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````

**Comment by konradfeketepayleven** [comment]
Hi,

Thanks for reaching out! 
From what I see, you tried to integrate through CocoaPods that hasn't been updated. 
Up until now, CocoaPods supported only the SDK version 1.1.0 that was not Bitcode enabled.
I apologize for any inconvenience this may have caused! 
From now on this shouldn't be a problem anymore as we just updated it. 
Please refer to:
pod 'Payleven-mPos', '~> 1.2.1' 

Best regards
