### ISSUE TITLE
Server error (406 Processing error)

### ISSUE THREAD

**Issue by mpodeszwa** [payleven/Point-Pay-SDK-iOS#9]
Hi,

I am getting error as above. It doesn't occur every time. Strangely, as far as I can tell, it has something to do with total amount to be paid. 

This payment request was passing every time:
```
let request = PLVPaymentRequest(identifier: identifier, amount: 1, currency: "EUR", coordinate: coordinate)
```
however request below was failing:
```
let request = PLVPaymentRequest(identifier: identifier, amount: 2, currency: "EUR", coordinate: coordinate)
```
In case you are logging every request, passing one had identifier `C5Yk2lDN` and failing `mbvdUfdV`

Thanks,
Marcin

**Comment by konradfeketesumup** [comment]
Hi Marcin,
could you please send the email address of your payleven merchant account to developer@payleven.com? I assume you have a test account that is limited to 1€ as total payment amount but I'd like to double check.

Thank you
Best

**Comment by konradfeketesumup** [comment]
Hi Marcin,
Thank you for sending me the email address of your merchant account.
My assumption was correct, your merchant account has been created by payleven for test purposes and is limited for this reason to 1€ for payments.
Best regards
